//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBFEntities : DbContext
    {
        public DBFEntities()
            : base("name=DBFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Queues> Queues { get; set; }
    
        public virtual ObjectResult<proc_GetCustomerByQueue_Result> proc_GetCustomerByQueue(Nullable<int> orderInQueue)
        {
            var orderInQueueParameter = orderInQueue.HasValue ?
                new ObjectParameter("OrderInQueue", orderInQueue) :
                new ObjectParameter("OrderInQueue", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<proc_GetCustomerByQueue_Result>("proc_GetCustomerByQueue", orderInQueueParameter);
        }
    }
}
